### ISSUE TITLE
Question about scheduling of maps over containers of known length

### ISSUE THREAD

**Issue by jgarvin** [rayon-rs/rayon#1000]
I read the FAQ and looked through the docs and couldn't find an answer to this but maybe I'm using the wrong search terms.

Say I have something like a Vec or a slice where we can `O(1)` query its length. If I do `slice.par_iter().map(|x| { ... })` and we ignore work stealing for the moment (assume every thread takes identical amount of time per element and the number of threads evenly divides the the number of elements to process), does each thread get a contiguous chunk of size `slice.len()/N` pushed on to its queue, or is each individual slice element round robinned across all threads? Two reasons I ask:

* For cache locality and prefetch, it's better for a thread to repeatedly handle elements close together in memory, ideally linearly.
* In my use case the items being iterated are keys used to query a thread local data structure, where often querying with `slice[i]` involves it internally loading and caching the data for `slice[i+1]`, so if the same thread subsequently does the query for `slice[i+1]` I will hit the cache.

This can't be done in all cases, because if what's feeding `map` is an opaque stream of values you don't have any idea up front how many elements are coming down the pipe, but for Vec/slice should be possible. I see there's a `Split` trait, but I'm not sure if that's intended for helping users manually force this kind of thing or if out of the box it's even necessary if the scheduling does this already. From the POV of my code it thinks it's only operating on one element at a time even though the thread local data structure internally loads query result for `slice[i+1]`, so using `chunks` feels artificial but maybe that's how I should guarantee this?

P.S. thanks for the sweet library :+1:

**Comment by cuviper** [comment]
At their core, parallel iterators work by nesting `join` -- split the work in two and call them in parallel by `rayon::join`, then merge the results when they're both done. Each `join` half then decides whether it should split further, and if not then it runs the actual work.

For a slice, that splitting is just using `split_at` or `split_at_mut`, so yes, they do ultimately work on contiguous chunks. They're not exactly `len() / N` each, because we're not assuming the ideal "identical amount of time per element", nor that the entire thread pool will be available to work on this particular iterator.

As you say, using contiguous slices is good for data locality, and it also makes it easy to preserve the overall order for `fold`/`reduce`/`collect`/etc., even though parallel execution is not ordered.

**Comment by jgarvin** [comment]
Thanks, that makes sense
