### ISSUE TITLE
Mutable iteration appears to be significantly slower than non-mutable

### ISSUE THREAD

**Issue by nazar-pc** [rayon-rs/rayon#1048]
I don't have a minimal reproduction yet, but behavior seemed odd so I decided to report.

I have some relatively heavy operation that should be parallelized and after some more idiomatic refactoring I found a few unexplained slowdowns.

Specifically I have changed `into_par_iter()` to `par_iter_mut()` and got a massive performance hit.

Code change: https://github.com/nazar-pc/subspace/commit/08007a2d7e8ca0976af8a01c053645160eee2303
```diff
--- a/crates/subspace-proof-of-space/src/chiapos/table.rs
+++ b/crates/subspace-proof-of-space/src/chiapos/table.rs
@@ -748,14 +748,14 @@ where
 
         let num_values = 1 << K;
         let mut t_n = Vec::with_capacity(num_values);
-        t_n.par_extend(buckets.into_par_iter().flat_map_iter(
-            |(left_bucket, right_bucket, mut rmap_scratch)| {
+        t_n.par_extend(buckets.par_iter_mut().flat_map_iter(
+            |(left_bucket, right_bucket, rmap_scratch)| {
                 let mut t_n = Vec::with_capacity(num_values);
                 match_and_compute_fn(
                     last_table,
-                    &left_bucket,
-                    &right_bucket,
-                    &mut rmap_scratch,
+                    left_bucket,
+                    right_bucket,
+                    rmap_scratch,
                     left_targets,
                 )
                 .collect_into(&mut t_n);
```

Before:
```
chia/table/parallel     time:   [54.325 ms 55.789 ms 57.104 ms]
```
After:
```
chia/table/parallel     time:   [82.533 ms 85.221 ms 87.182 ms]
```

Can be benched by cloning the repo and running this:
```
cd crates/subspace-proof-of-space
cargo bench --features=chia,parallel -- --sample-size 10 chia/table/parallel
```

I do not quite understand what is going on here that would be so significant.

**Comment by adamreichold** [comment]
I do not know what kind of data structures are stored in `buckets`, but the above change makes their `Drop` impls run serially instead of in parallel before the change. Meaning that the items stored in `buckets` were moved into the closures pass to `flat_map_iter` and their `Drop` impls called as the end of that closure, i.e. on the thread pool.

You might be able to test that hypothesis by storing `Option<T>` instead of `T` inside `buckets` and `.take()`ing them out inside the `par_iter_mut()` variant so that the `Drop` impls are run in parallel again even.

**Comment by nazar-pc** [comment]
Very nice, it was indeed dropping of significant number of elements that was causing this. Thank you!
