### ISSUE TITLE
Stop ParallelIterator sooner

### ISSUE THREAD

**Issue by skyf0l** [rayon-rs/rayon#1067]
I'm using a `ParallelIterator` to perform a long search process and I want it to stop once a value is found. But it actually stops once the whole "chuck" is calculated. This is not what I want because some search processes take far too long or may run indefinitely.

The following code will explain my problem:

```rust
use rayon::prelude::{IntoParallelRefIterator, ParallelIterator};
use std::time::Duration;

fn main() {
    let data = vec![1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

    let value = data
        .par_iter()
        .find_map_any(|v| {
            println!("Thread: {:?} sleep: {}", std::thread::current().id(), v);
            std::thread::sleep(Duration::from_secs(*v));
            println!("Thread: {:?} wake up: {}", std::thread::current().id(), v);
            if *v == 5 {
                Some(5)
            } else {
                None
            }
        })
        .unwrap();

    println!("Find value: {value}");
}
```

With its output:

```
Thread: ThreadId(6) sleep: 2
Thread: ThreadId(8) sleep: 1
Thread: ThreadId(11) sleep: 6
Thread: ThreadId(2) sleep: 8
Thread: ThreadId(4) sleep: 9
Thread: ThreadId(9) sleep: 7
Thread: ThreadId(10) sleep: 3
Thread: ThreadId(12) sleep: 4
Thread: ThreadId(3) sleep: 10
Thread: ThreadId(7) sleep: 5
Thread: ThreadId(8) wake up: 1
Thread: ThreadId(6) wake up: 2
Thread: ThreadId(10) wake up: 3
Thread: ThreadId(12) wake up: 4
Thread: ThreadId(7) wake up: 5
Thread: ThreadId(11) wake up: 6
Thread: ThreadId(9) wake up: 7
Thread: ThreadId(2) wake up: 8
Thread: ThreadId(4) wake up: 9
Thread: ThreadId(3) wake up: 10
Find value: 5
```

And my expected output must be:

```
Thread: ThreadId(6) sleep: 2
Thread: ThreadId(8) sleep: 1
Thread: ThreadId(11) sleep: 6
Thread: ThreadId(2) sleep: 8
Thread: ThreadId(4) sleep: 9
Thread: ThreadId(9) sleep: 7
Thread: ThreadId(10) sleep: 3
Thread: ThreadId(12) sleep: 4
Thread: ThreadId(3) sleep: 10
Thread: ThreadId(7) sleep: 5
Thread: ThreadId(8) wake up: 1
Thread: ThreadId(6) wake up: 2
Thread: ThreadId(10) wake up: 3
Thread: ThreadId(12) wake up: 4
Thread: ThreadId(7) wake up: 5
Find value: 5
```

I expect the iterator to break immediately once the filter is satisfied.

**Comment by cuviper** [comment]
> I expect the iterator to break immediately once the filter is satisfied.

Even while the other ones are still sleeping? We can't do that, because those have borrowed from `data` in their `v`, and there's no way to interrupt a closure call -- it's a black box to rayon. As a library (not compiler-integrated), we don't even know whether you really are doing anything with borrowed data. You *could* be, so we must allow for it.

(The particular fact that they are sleeping is not really relevant... they could be in a busy loop, or making a network request, or performing a hard calculation that must not be interrupted. It's all opaque to rayon.)

The only opportunity we have to short-circuit is when you return execution from the closure back to rayon, then we can avoid starting any new items.

> This is not what I want because some search processes take far too long or may run indefinitely.

You could add your own `AtomicBool` state to be used by the closure, and check that at strategic break points in your search processes.
