### ISSUE TITLE
Use more specific error types than `Box<std::error::Error>`

### ISSUE THREAD

**Issue by Binero** [rayon-rs/rayon#403]
There is a couple of points in this library where it emits a generic `Box<std::error::Error>` as opposed to a specific error type, and it does this for no apparent reason. 

An example of where this happens is while [creating a new `Registry`](https://github.com/nikomatsakis/rayon/blob/3eaba54e31788ebc728f5795dba6bdf4e88c981f/rayon-core/src/registry.rs#L113). Even though this function can only ever return `std::io::Error`, it returns a `Box<std::error::Error>`.

Registry not returning a proper error propagates to other types as well, for instance to `ThreadPool`. 

There are two paths we could take, but both would be breaking changes.
 - We create a custom `RegistryCreation` error type, which for now just wraps around `std::io::Error`, but can be extended in the future.
 - We are confident that function will never return any other type of error without also requiring a breaking change. We use `std::io::Error` directly.

**Comment by cuviper** [comment]
This was done simply to ease flexibility, as we were stabilizing `rayon-core`.  We didn't want to be stuck if some new unforeseen error condition ever came up.

You're right that a `RegistryCreation` newtype could have abstracted this, and I'm not sure why we didn't go that way.  Maybe because there are multiple layers here, e.g. `Registry::new` has its errors, and then `init_global_registry` adds a `GlobalPoolAlreadyInitialized` error.

But `rayon-core` is now 1.0, and we explicitly want to avoid fragmenting so that the global threadpool is always shared.  I think we won't make any breaking change here without a very strong justification.  `Box<Error>` seems like a pretty minor wart to me.

**Comment by Binero** [comment]
I agree that it's not worth to make a breaking release for just this issue, but it's worth considering when inevitably a future breaking release does happen.

**Comment by nikomatsakis** [comment]
closing in favor of https://github.com/rayon-rs/rayon/issues/417 since there is more discussion there
