### ISSUE TITLE
What's the meaning of with_min_len with zip and flat_map?

### ISSUE THREAD

**Issue by pornel** [rayon-rs/rayon#472]
The documentation of `with_min_len` doesn't explain how multiple values of `with_min_len` interact, e.g.

```rust
vec.par_iter().with_min_len(a)
.zip(vec2.par_iter().with_min_len(b))
.flat_map(|_| {
  other.par_iter().with_min_len(c)
});
```

**Comment by cuviper** [comment]
Good question!  This comes from the implementation of `Producer::min_len`.  For producers like `zip` and `interleave` which must drive two iterators in tandem, they will return the greater of the two minimums.  Similarly, `max_len` takes the lesser of two maximums.  For your example, the effective minimum will be `cmp::max(a, b)`.

The `chain` producer will also act like this, but usually `chain` avoids becoming a producer at all, instead driving each of its iterators independently.  In that case, they'll each get their independent `min_len` applied.  But if `chain` is an argument to a `zip` or `interleave`, then it must be a producer too.

The `flat_map` you show is interesting because this doesn't directly act like a producer itself at all, but every iterator it returns will be driven independently.  You could in theory use a different `c` each time it's called, and they'll each respect that value.
