### ISSUE TITLE
implementing opt_len for ParallelIterator causes panic

### ISSUE THREAD

**Issue by m4b** [rayon-rs/rayon#500]
I just implemented because I had the information, but it causes this error:

```
'main' panicked at 'internal error: entered unreachable code: CollectConsumer must be indexed!',
```

when I use a `bridge_unindexed` call in `drive_unindexed` impl

Maybe I'm doing something wrong but didn't see any docs explicitly forbidding this. Sorry if I missed it!

**Comment by cuviper** [comment]
It's a bit of a hacky thing, and perhaps we need to describe it better, but the docs for [`opt_len`](https://docs.rs/rayon/0.9.0/rayon/iter/trait.ParallelIterator.html#method.opt_len) state that if you return `Some`, you should not call methods of `UnindexedConsumer`. But `bridge_unindexed` will do exactly that.

So you should only implement `opt_len` if you know the length *and* can drive like it's indexed. This is currently only used to optimize `collect::<Vec<_>>()`, otherwise it's no loss to leave this as the default `None`.

**Comment by m4b** [comment]
Derp, sorry, don't know how I missed that, was looking at the str module for inspiration and was copying its style of implementation.

This probably isn't the right forum, and I should probably read more, but is the general idea that drive_indexed is for when you can efficiently index into the structure you're parallel iterating (and so you should use that instead)?

I ask because I have an unindexed implementation now, but I can efficiently index so i don't know which one I should choose for my datastructure.

**Comment by cuviper** [comment]
Implementing it indexed will enable all of the `IndexedParallelIterator` methods, like `zip` and `enumerate`. For `str` we don't do this because there's not an efficient way to index UTF-8 characters, but if your data structure allows it, I would definitely go that way.

**Comment by m4b** [comment]
Cool!  I think can close this issue unless want to keep open for some reason :)

**Comment by cuviper** [comment]
OK! Drop us a note in gitter or something if you want to share what it is you're parallelizing.
