### ISSUE TITLE
Support for Zipping multiple array

### ISSUE THREAD

**Issue by rohitjoshi** [rayon-rs/rayon#567]
I am currently using `rayon` iterator for zipping two arrays. I need to zip multiple arrays and a combination of rayon and `itertools` will definitely help.  for now, I had to switch to `itertools` which is sequential.

See the similar request on [itertools](https://github.com/bluss/rust-itertools/issues/271)

**Comment by cuviper** [comment]
Combining rayon with generic iterators (including itertools) is a hard problem -- #46.

But specifically for zipping, I suppose you mean something like itertools' `izip!()` and `multizip()`?  I think this would be feasible to recreate in rayon.

**Comment by rohitjoshi** [comment]
yes, `izip!()` and `multizip()`

**Comment by MaikKlein** [comment]
@cuviper Is anyone working on it? If not I could probably implement it, I don't think it would require much work. I'd probably change the signature from `Zip<A, B>` to `Zip<Tuple>`, and then implement iterator for the various zips `Zip<(A, B)>` etc.

**Comment by cuviper** [comment]
@MaikKlein I don't know of anyone working on it.  I don't think we would want to make a breaking change to the existing `Zip`, so this should probably be added as a new thing.

**Comment by cuviper** [comment]
I'm working on this now...

**Comment by dineshadepu** [comment]
Hello @cuviper, is there any chance of adding to rayon in future?

**Comment by cuviper** [comment]
Well, clearly I stopped working on it, sorry about that. I just found my WIP branch and pushed it to my fork though, if anyone would like to pick that up and finish it:

branch: https://github.com/cuviper/rayon/tree/multizip
comparison: https://github.com/rayon-rs/rayon/compare/master...cuviper:multizip

**Comment by dineshadepu** [comment]
It looks complete, and the documentation states all the use cases. I think I can use it in my code base. Can I know what else is there to add?

**Comment by cuviper** [comment]
I honestly don't know what I though was remaining... :confused:

**Comment by dineshadepu** [comment]
Hi Josh,

I am using it in my crate as in here https://github.com/multiphase-rs/mulltiphase_rs/blob/master/src/dem/mod.rs#L50 and many other places which is not yet open source, by creating another package https://github.com/multiphase-rs/rayon.

Please try to add it to the upcoming release of rayon.

Thank you.

**Comment by cuviper** [comment]
Now that I look again, I'm not really happy with that function signature:

```rust

pub fn multizip<T, I>(tuple: T) -> MultiZip<I>
where
    T: IntoParallelIterator<Iter = MultiZip<I>>,
    MultiZip<I>: ParallelIterator<Item = T::Item>,
{
    tuple.into_par_iter()
}
```

Having `I` as a type parameter implies that it can be chosen, but it's actually locked to the exact type from `T`'s `Iter = MultiZip<I>`. The design of [`itertools::multizip`](https://docs.rs/itertools/0.8.2/itertools/fn.multizip.html) is similar, but they have an additional constraint. They can't implement a foreign trait (`IntoIterator`) for a foreign type (tuples), which is why theirs ends up based on `From`.

In our case, we defined `IntoParallelIterator`, so we're free to implement it directly on tuples and their references, thus you can call `into_par_iter()`, `par_iter()`, and `par_iter_mut()` directly on the tuple. I think we don't really need a `multizip` function at all.

I'm going to remove that and clean up the examples to match, then I'll open a PR. We can always add such a function later if there's a compelling case.

**Comment by rohitjoshi** [comment]
Thanks
