### ISSUE TITLE
Passing Crossbeam channel into ThreadPoolBuilder

### ISSUE THREAD

**Issue by daharon** [rayon-rs/rayon#619]
I have a program that passes items to be processed by threads in a thread-pool via the `crossbeam-channel` crate.
I'm trying to use Rayon's `ThreadPool` to manage the worker threads.
My problem is that I can't figure out how to pass the channel receiver into the `ThreadPoolBuilder`'s `start_handler`.

```rust
    // Create channels for stream-handler to worker threads.
    let (sender, receiver) = crossbeam_channel::bounded::<String>(CHANNEL_CAPACITY);

    // Start worker thread-pool.
    let _pool = rayon::ThreadPoolBuilder::new()
        .num_threads(NUM_THREADS)
        .thread_name(|index| format!("worker-thread-{}", index))
        .start_handler(|_| {
            let w_receiver = receiver.clone();
            worker_func(w_receiver);
        })
        .build()
        .expect("Failed to instantiate thread-pool.");
```

```
error[E0373]: closure may outlive the current function, but it borrows `receiver`, which is owned by the current function
  --> src/server.rs:34:24
   |
34 |         .start_handler(|_| {
   |                        ^^^ may outlive borrowed value `receiver`
35 |             let w_receiver = receiver.clone();
   |                              -------- `receiver` is borrowed here
   |
note: function requires argument type to outlive `'static`
  --> src/server.rs:31:17
   |
31 |       let _pool = rayon::ThreadPoolBuilder::new()
   |  _________________^
32 | |         .num_threads(NUM_THREADS)
33 | |         .thread_name(|index| format!("worker-thread-{}", index))
34 | |         .start_handler(|_| {
...  |
37 | |             worker_func(w_receiver);
38 | |         })
   | |__________^
help: to force the closure to take ownership of `receiver` (and any other referenced variables), use the `move` keyword
   |
34 |         .start_handler(move |_| {
   |                        ^^^^^^^^
```

Now, I know _why_ what I'm trying to do will not work.
But I don't know how to do it correctly.

How can I pass something like this channel or an `Arc` into my worker threads?

**Comment by daharon** [comment]
@stjepang, that does work.
I was under the impression that if I `move`'d the variable into the closure, then the first thread to spawn would take ownership of the `receiver` and subsequent threads would not be able to start.

I guess I don't understand how the `start_handler` works.
Thanks!

**Comment by cuviper** [comment]
The `move` keyword only changes how values are captured, so they are owned in the closure environment rather than referenced (with some lifetime). But if the closure body only uses those values by reference, it will still implement `Fn` that can be shared and called multiple times.

**Comment by cuviper** [comment]
Rayon doesn't restart its threads, but it does guard for panic safety. Calls like `install`, `join`, and `scope` will propagate panics to the caller, allowing the pool to continue to other tasks. Unscoped `spawn` will call the `panic_handler` if set, otherwise abort.

I suppose you could use that handler to spawn a new channel listener. But if you've got all threads waiting on a channel, then they won't be participating in task-stealing, which defeats most of the point of rayon over simpler thread pools. I'm suggesting that instead of the channel, you could use direct spawns for each of your items, and rayon can spread that work around.

(An actual crash in a thread will take down the whole process, which rayon can't help you with.)
