### ISSUE TITLE
Out of date flags in the Development Guide section of the wiki

### ISSUE THREAD

**Issue by seanchen1991** [rayon-rs/rayon#622]
After forking and attempting to run `cargo test --features unstable` locally, I get a `rayon does not have these features: unstable` error. Running without the unstable flag seems to work perfectly fine; no warnings about dead code in sight. I can go and update the cargo commands in the wiki if y'all are fine with removing the `--features unstable` flag.

**Comment by cuviper** [comment]
Hmm, yes, we switched that to a manual `cfg` flag a while ago (#371). These days it's only used for futures integration, which is why it's only described in [the rayon-futures README](https://github.com/rayon-rs/rayon/blob/master/rayon-futures/README.md). We no longer need to advise using that all the time. You can now also use stable rustc for testing and the demos, although I suppose you still need nightly for benchmarks.

**Comment by nikomatsakis** [comment]
We have a wiki? :) I forgot all about that.

**Comment by nikomatsakis** [comment]
I removed the mention of `--features unstable`, at least. Closing this issue for now. Thanks @seanchen1991 !
