### ISSUE TITLE
Trying to implement ParallelIterator for a custom struct

### ISSUE THREAD

**Issue by Gymmasssorla** [rayon-rs/rayon#643]
I am trying to implement the `ParallelIterator` trait for my own custom type, and this is how it should look in case of the standard `Iterator`:

```rust
struct CustomIterator {
    number: i32
}

impl Iterator for CustomIterator {
    type Item = i32;

    fn next(&mut self) -> Option<Self::Item> {
        self.number += 5;
        Some(self.number)
    }
}
```

The main question is "How I should implement `ParallelIterator` for `CustomIterator`?"

**Comment by cuviper** [comment]
It's definitely not as simple as a normal `Iterator`!

The first question to ask is how you will *split* your iterator for parallel processing. The `CustomIterator` you've shown here won't work because it is unbounded, just as we don't implement `ParallelIterator` for `RangeFrom`. If you had an endpoint, you could split your iterator in half, which gives you the means to implement an internal `Producer`.

If you can implement your iterator in terms of existing iterators, this is easiest, perhaps like:

```rust
use rayon::iter::plumbing::*;
use rayon::prelude::*;

pub struct StepBy5 {
    start: i32,
    end: i32,
}

impl ParallelIterator for StepBy5 {
    type Item = i32;

    fn drive_unindexed<C>(self, consumer: C) -> C::Result
    where
        C: UnindexedConsumer<Self::Item>,
    {
        let StepBy5 { start, end } = self;

        // Start with a simple range, then map it to increment by 5
        (0..(end - start + 4) / 5)
            .into_par_iter()
            .map(|i| start + i * 5)
            .drive_unindexed(consumer)
    }
}
```

Otherwise, I would use an existing implementation as a reference, and read [plumbing/README.md](https://github.com/rayon-rs/rayon/blob/master/src/iter/plumbing/README.md). You could also consider using one of the wrappers like [`split()`](https://docs.rs/rayon/1.0.3/rayon/iter/fn.split.html) or [`par_bridge()`](https://docs.rs/rayon/1.0.3/rayon/iter/trait.ParallelBridge.html).

**Comment by Gymmasssorla** [comment]
Thank you very much, now I think I understand it.
