### ISSUE TITLE
Performance problems

### ISSUE THREAD

**Issue by D4Delta** [rayon-rs/rayon#658]
Hi, I just discovered rust and rayon, and wrote a trivial program to generate primes:
```
extern crate rayon;

use std::collections::LinkedList;

use rayon::prelude::*;

fn main() {
    let prime_list = par_primes(100000);
    for i in prime_list {
        println!("{}", i);
    }
}

fn primes(n : u32) -> LinkedList<u32> {
    let mut primes = LinkedList::new();

    for i in 2..n {
        if primes.iter().all(|&x| i % x != 0) {
            primes.push_back(i);
        }
    }
    primes
}

fn par_primes(n : u32) -> LinkedList<u32> {
    let mut primes = LinkedList::new();
    for i in 2..n {
        let is_prime = primes.par_iter().all(|&x| i % x != 0);
        if is_prime {
            primes.push_back(i);
        }
    }
    primes
}
```

I expected an increase in performance, but, the parallel version was way slower:

Parallel:
```
real    0m2,201s
user    0m4,403s
sys     0m3,689s
```

Single-threaded:
```
real    0m0,128s
user    0m0,127s
sys     0m0,000s
```
I tried this multiple time, on different machines, but the result stays the same.

What am I doing wrong ?

**Comment by cuviper** [comment]
I would first suggest that `LinkedList` is a bad choice in both cases. This will scatter the primes over many separate heap allocations, whereas a `Vec` would hold them in one contiguous allocation, which is much better for memory performance.

But it's even worse for `par_iter()` -- since `LinkedList` doesn't support random access, we actually end up creating a shadow `Vec` of references to your list items, then parallel iterate through that. This could be reasonable in isolation, but you're repeating this 100,000 times! This part will be **much** faster if the list of primes is a `Vec` to begin with.

Even then, I think this is a bad case for parallelization. In the serial case, half of the numbers tested will be ruled out immediately by the 2 factor, and a third will be ruled out by 3, etc. -- most are ruled out by small primes. Spinning up any kind of cross-thread synchronization will swamp that in overhead.

A different strategy you can take is to parallelize the numbers being checked, and you can do this by taking advantage of the fact that the smallest factor of a composite number must be less than or equal to its square root. For instance, sqrt(35) = 5.916... and you would find 5 as a divisor; sqrt(37) = 6.082... so once you've tried primes {2,3,5}, there's no point checking {7,11,...}, therefore 37 is prime. This is also a useful shortcut in your serial case.

So I would parallelize primes up to a million roughly like this:

```rust
let small_primes: Vec<u32> = get_serial_primes_to(1000);
let mut primes = small_primes.clone();
primes.par_extend((1001..1_000_000).into_par_iter().filter(|n| {
    small_primes
        .iter()
        .take_while(|&&p| p * p <= n)
        .all(|&p| n % p != 0)
}));
```

There are **lots** of possible optimizations around generating primes -- the [`primal` crate](https://crates.io/crates/primal) is still probably faster than this, even though it's completely serial. Still, this should give you some ideas how to use parallelism effectively.

**Comment by D4Delta** [comment]
Thank you very much for the detailed explanation.
