### ISSUE TITLE
Performance isn't improving

### ISSUE THREAD

**Issue by yardenfi** [rayon-rs/rayon#659]
Hi,
I'v written  a little bit of code that I think could benefit performance-wise from using rayon, but when I tried it, I discovered it didn't.
the code does this:
I'v got an md5 of a number between 1 and 10000000, and I need to find what it is by checking each number in this range.
```rust
#![feature(test)]
extern crate rayon;
extern crate test;

use std::time::SystemTime;

use md5;
use md5::Digest;
use rayon::prelude::*;

fn is_same(checked: f64, digest: Digest) -> bool {
    md5::compute(checked.to_string().into_bytes()) == digest
}


fn main() {

    let timeit = SystemTime::now();
    println!("counting in parallel:");
    println!("result: {:?}", (1..10000000).into_iter()
        .find(|num: &i32| {
            is_same((*num) as f64, md5::compute(1234567.to_string().into_bytes()))
        }));
    println!("it took {:?} seconds.", SystemTime::now().duration_since(timeit).unwrap());

    let timeit = SystemTime::now();
    println!("result: {:?}", (1..10000000).into_par_iter()
        .find_any(|num: &i32| {
            is_same((*num) as f64, md5::compute(1234567.to_string().into_bytes()))
        }));
    println!("it took {:?} seconds.", SystemTime::now().duration_since(timeit).unwrap());
}
```

For some reason, trying this on my computer give worse results when using parallel.
can someone please explain this?

**Comment by cuviper** [comment]
When you search for a match on 1234567, the serial version only computes exactly 1234567 items and stops. The parallel version will divide the range into smaller ranges, so all the computation it does on the higher portion of the range is extra work that the serial version skips. While it will still stop as soon as a match is found anywhere, that's still some extra used CPU resources. If your machine has SMT, like Intel hyper-threading, then that extra work on one thread can actively slow down other threads competing for resources on the same core.

However, if I change your search value to 7654321, the parallel version is consistently faster. Now it's a benefit to have some threads working on the high end of the range, whereas the serial version has to process all the way from the beginning.

Another option is to use `par_bridge()` on the range instead, so items are basically distributed in parallel from the beginning of the iterator. The bridge adds some overhead compared to `into_par_iter()`, but it's small compared to the md5 work you're doing, so that's OK. I find that this is indeed faster than the serial version at finding 1234567. It's also faster for 7654321, but not as fast as the pure parallel version.

Results on my laptop i7-7600U (2 cores, 4 logical threads):

```text
finding with iter():
result: Some(1234567)
it took 514.543215ms seconds.

finding with into_par_iter():
result: Some(1234567)
it took 980.925067ms seconds.

finding with par_bridge():
result: Some(1234567)
it took 274.061157ms seconds.
```

```text
finding with iter():
result: Some(7654321)
it took 3.165408314s seconds.

finding with into_par_iter():
result: Some(7654321)
it took 123.41093ms seconds.

finding with par_bridge():
result: Some(7654321)
it took 1.743722778s seconds.
```

**Comment by cuviper** [comment]
Here's another result searching for 0, so they have to compute *everything* and won't find it:

```text
finding with iter():
result: None
it took 4.124399588s seconds.

finding with into_par_iter():
result: None
it took 2.014241121s seconds.

finding with par_bridge():
result: None
it took 2.217921687s seconds.
```

**Comment by wagnerf42** [comment]
you can do a sequential iterator on blocks of ranges (using step by for example) and then map each block to a parallel find and do a sequential find on the mapped iterator

**Comment by cuviper** [comment]
@yardenfi - please feel free to re-open if you have further questions.
