### ISSUE TITLE
Question about behavior of spawn and thread-pool.

### ISSUE THREAD

**Issue by gterzian** [rayon-rs/rayon#724]
I have a couple of somewhat independent structs that I would like each to be able to spawn work on the same thread-pool. 

I did not see an API to clone or get an handle to a thread-pool that one would have configured with a builder, but I read that `rayon::spawn` will spawn work "on the global or static threadpool". 

However, looking at https://github.com/rayon-rs/rayon/blob/7ffaf3463be2339cb5bad86dc87b602ed067fc7c/rayon-core/src/registry.rs#L268

It appears to me that if the global thead-pool hasn't been set yet, `rayon::spawn` could actually result in setting a new thread-pool as the global one? 

So let's say that in a given process, I first build a thread pool, and then I  want to use `rayon::spawn`, is that going to actually build a new thread-pool or use the one that was configured before? 

Do I need to use `build_global` to get this behavior?

Or would it be best to simply pass the `ThreadPool` around using (A)Rc?

**Comment by cuviper** [comment]
There is an implicit global thread pool which is used by default. It will automatically be initialized on first use, or you can configure that yourself with `ThreadPoolBuilder::build_global`. You can also build standalone instances of `ThreadPool` that will run independently of the global pool.

When you call a global function like `rayon::spawn`, the thread pool is chosen by the caller's thread context. If this is called within a thread that is already part of a pool, whether global or other, then the `spawn` will be directed to that same pool; otherwise, the `spawn` will use the global pool. There is also a `ThreadPool::spawn` method which can target a particular pool regardless of where you're calling from.

> It appears to me that if the global thead-pool hasn't been set yet, `rayon::spawn` could actually result in setting a new thread-pool as the global one?

Right, if the global pool doesn't exist yet, it will be created and remain for the rest of the process life.

> So let's say that in a given process, I first build a thread pool, and then I want to use `rayon::spawn`, is that going to actually build a new thread-pool or use the one that was configured before?
> 
> Do I need to use `build_global` to get this behavior?

If you want your configuration used for all "loose" `rayon::spawn` calls, then yes `build_global` should work. The only exception would be if `spawn` were called from a thread in a different pool, then it will stay in that pool.

You could also use `ThreadPool::spawn`, or use `ThreadPool::install` to enter the pool such that further `rayon::spawn` calls will stay in that pool.

> Or would it be best to simply pass the `ThreadPool` around using (A)Rc?

Not sure -- I guess "best" depends on whether you want to have a global effect or not.

**Comment by gterzian** [comment]
Ok thanks for the info!

**Comment by cuviper** [comment]
Feel free to reopen if you have followup questions.
