### ISSUE TITLE
How to run function in global threadpool?

### ISSUE THREAD

**Issue by jerryc05** [rayon-rs/rayon#758]
Just a very quick question, how do I run a function in the global thread pool of `rayon`?

I have searched for a while but got nothing.

I am using `rayon v1.3.0`.

Thanks.

**Comment by jerryc05** [comment]
Or global threadpools are used for those `par_iter()` thing?

**Comment by cuviper** [comment]
The global threadpool is used whenever you call a rayon function that's supposed to run in the pool, when there's no explicit pool in context.

Explicit use would be something like `ThreadPool::join`, which will run on that particular pool. Contextual use would be a "loose" call like `rayon::join` -- if you call this from within a pool already, it will continue on that pool, otherwise it will use the global pool.

**Comment by jerryc05** [comment]
thx
