### ISSUE TITLE
Efficiently combining rayon with separate ui/render thread

### ISSUE THREAD

**Issue by DzmitryFil** [rayon-rs/rayon#780]
Given - render thread that uses opengl, and rayon thread pool. What i would like to do, is somehow combine this render thread with rayon pool in an async fashion with specific sync points. For instance: 
create rayon scope to execute bunch of jobs in specific order from render thread, but do not block immediately waiting for this scope to be done, but instead do some useful work with opengl. I understand that i would not be able to exit the function that created scope, because it can reference stack, but i would like to at least have the ability to not block immediately. Can this be done?
Also, am i correct in that rayon::join will always execute first function on the caller thread, when called from the thread_pool, and Send restriction for the first function can be effectively ignored (via some unsafe wrapper) in that specific case?

**Comment by cuviper** [comment]
> create rayon scope to execute bunch of jobs in specific order from render thread, but do not block immediately waiting for this scope to be done, but instead do some useful work with opengl. I understand that i would not be able to exit the function that created scope, because it can reference stack, but i would like to at least have the ability to not block immediately.

We do have to block the return from `scope` until all its spawns are done, otherwise there's no way to guarantee that you don't leave the function, as you say. You can read this [classic post](http://cglab.ca/~abeinges/blah/everyone-poops/) on how that affected `std::thread::scoped`, which had to be removed before Rust 1.0. The callback style is how we can **guarantee** that code runs (and blocks) before the scope is invalidated.

I think what you could use is something like #562, where the `scope` closure would execute directly. So you'd `spawn` your tasks and then do your extra opengl work all in that same closure, returning when you're ready to let it block. You could use a side channel to know that everything is done, so it won't block, or we might even be able to make that a method on the `Scope`.

> Also, am i correct in that rayon::join will always execute first function on the caller thread, when called from the thread_pool, and Send restriction for the first function can be effectively ignored (via some unsafe wrapper) in that specific case?

Yes, but "when called from the thread pool" is critical -- I'd be really wary of hacking around that in `unsafe`. We could revisit #20, where the first closure could be non-`Send` and always be executed directly, whether you're in the pool or not.

**Comment by DzmitryFil** [comment]
Thank you, for such a detailed answer! I understand the scope of the problem better now, I'm going to close this in favor of issues you mentioned.
