### ISSUE TITLE
panic handler behavior

### ISSUE THREAD

**Issue by nilgoyette** [rayon-rs/rayon#825]
I wrote this simple snippet to test the `panic_handler`

    use ndarray::{Array2, Array3, ArrayView2, Axis};
    use rayon::ThreadPoolBuilder;
    let panic_handler = |_| {
        println!("############ Test ############");
    };
    ThreadPoolBuilder::new().num_threads(4).panic_handler(panic_handler).build_global().unwrap();

    let data = Array3::zeros((100, 100, 100));
    Zip::from(data.axis_iter(Axis(2))).par_apply(|slice: ArrayView2<f32>| {
        panic!("Hola");
    });

The threads do panic. I see several errors messages that look like

    thread 'thread 'thread 'thread '<unnamed><unnamed><unnamed><unnamed>' panicked at '' panicked at '' panicked at '' panicked at 'HolaHolaHolaHola', ', ', ', test.rstest.rstest.rstest.rs::::10101010::::9999
    idem
    ...

However, I never see my `panic_handler` message. Why? Isn't this exactly the goal of a panic_handler?

Moreover, why do I see that many error messages? I understand that each thread must end or panic before quitting, but it looks like rayon is trying and trying again to run what I asked in `Zip::from`. Can I ask rayon to never retry? To leave as soon as there an error?

**Comment by cuviper** [comment]
In most cases, we propagate panics back to the caller, and rayon threads stay alive to run whatever job is next. You could catch such a panic and recover, so we want the pool to still be in a usable state. We can't propagate panics in detached calls though, namely unscoped `spawn`, so those go to the panic handler, which aborts by default.

For scoped calls, like `join` and `Scope::spawn`, we have to make sure that we don't return until all jobs in that borrowed scope have completed. If one half of a `join` panics, we still must let the other half finish before we continue unwinding, otherwise that other half (which may be on a different thread) could be left with dangling references.

Most of the parallel iterators are implemented with nested `join` calls, so that's why you'll see a lot more attempts to run, for parts that were already split from the first thing that panicked. We don't have any cancellation flags in general, but there is the [`panic_fuse()`](https://docs.rs/rayon/1.5.0/rayon/iter/trait.ParallelIterator.html#method.panic_fuse) method on iterator chains to make them stop more aggressively. But `par_apply` comes from `ndarray`, so you'd have to ask them to implement something similar.

**Comment by nilgoyette** [comment]
Ok, thank you, I understand why there are so many error messages. I'm still unsure about the panic handler though.

>We can't propagate panics in detached calls though, namely unscoped spawn, so those go to the panic handler, which aborts by default.

If I understand correctly, `Zip::par_apply` is a "detached call" and thus a panic is propagated to a hardcoded panic handler? My toy `panic_handler` would work only with `join` and `Scope::spawn`?

**Comment by cuviper** [comment]
No, `par_apply` is still a blocking call, built on regular parallel iterators underneath, and `join` blocks as well. `Scope::spawn` doesn't immediately block, but it will at the end of that `scope`, so panics can propagate there.

By contrast, the global `spawn` queues work without waiting for it, so we don't have any caller to propagate to if it does panic when that finally runs. That's what I meant by "detached", and this is the case that uses your panic handler. I think the global `spawn`, `spawn_fifo`, and their `ThreadPool` equivalents are the only such calls.

Maybe you would like the standard hook to get _all_ panics?
https://doc.rust-lang.org/std/panic/fn.set_hook.html

**Comment by nilgoyette** [comment]
Oh, ok, it's clearer now :) Thank you!
