### ISSUE TITLE
IntoParallelIterator for Range breaks type inference

### ISSUE THREAD

**Issue by kmdreko** [rayon-rs/rayon#833]
Motivated by [this stack overflow question](https://stackoverflow.com/questions/66666909/why-does-filter-have-different-type-requirements-on-parallel-iterators):

```
use rayon::prelude::*;

fn is_even(n: i64) -> bool {
    n % 2 == 0
}

fn main() {
    let v: Vec<_> = (1..300_000_000)
        .into_par_iter() // works correctly without this line
        .filter(|&x| is_even(x))
        .collect();
}
```

```
error[E0271]: type mismatch resolving `<rayon::range::Iter<i32> as rayon::iter::ParallelIterator>::Item == i64`
  --> src/main.rs:11:10
   |
11 |         .filter(|&x| is_even(x))
   |          ^^^^^^ expected `i32`, found `i64`

error[E0271]: type mismatch resolving `<rayon::range::Iter<i32> as rayon::iter::ParallelIterator>::Item == i64`
  --> src/main.rs:12:10
   |
12 |         .collect();
   |          ^^^^^^^ expected `i32`, found `i64`
   |
   = note: required because of the requirements on the impl of `rayon::iter::ParallelIterator` for `rayon::iter::Filter<rayon::range::Iter<i32>, [closure@src/main.rs:11:17: 11:32]>`
```

My assessment was that this was due to how `ParallelIterator` is defined for `range::Iter` and a fix was *possible*, but I don't know enough about rayon internals to know if there's a significant motivating factor for doing it this way.

**Comment by cuviper** [comment]
Hmm, I would have hoped the compiler could be clever enough to figure that out as-is, but I'd be willing to make tweaks in rayon if we can do so without breaking changes. For posterity, here are your "reconstruction" playgrounds again: [non-working](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=878add570de6759df7ed3b1ddda7af78) when it looks like rayon today, and [working](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1d9f14b5aedfefdbec6f138079833bc7) when you make `ParallelIterator` share a generic implementation.

There are interesting differences in the implementations for each type, which doesn't get captured in your reconstruction. Particularly, those `Range<T>` that implement `ExactSizeIterator` can also implement `IndexedParallelIterator`, depending on how the integer type relates to 32/64-bit `usize`. (16-bit `usize` isn't considered.) There's also a `Range<char>` implementation which is quite different still.

I think we could do this with something like an internal `T: ParallelRange` trait, and then delegate the `ParallelIterator` implementation to that. (And repeat for `Indexed`...) It seems odd that an extra layer of indirection would help inference, but I suppose the point is that it gets to prove a constraint directly about the unknown `T` instead of `Iter<T>`, right?

**Comment by cuviper** [comment]
#834 seems to work, if you care to take a look.
