### ISSUE TITLE
Storing `scope` in a struct

### ISSUE THREAD

**Issue by kontheocharis** [rayon-rs/rayon#871]
Hello there. I'm having some trouble storing `rayon::Scope` inside a struct, while being able to store values of other lifetimes in the struct. I'm trying to create another instance of the same struct inside a spawned scope, but I am faced with lifetime issues, relating to the `|scope| {...` closure outliving the `'scope_ref` lifetime. Is there any way to do this, or is there some type of limitation with the signature of `scope.spawn`? Any help would be greatly appreciated.

Code:
```rs
use rayon::Scope;

struct Test<'scope_ref, 'scope, 'value> {
    value: &'value usize,
    scope: &'scope_ref Scope<'scope>,
}

impl<'scope_ref, 'scope, 'value> Test<'scope_ref, 'scope, 'value>
where
    'scope: 'scope_ref,
    'value: 'scope,
{
    fn test(&self) {
        self.scope.spawn(|scope| {
            let t = Test { scope, value: self.value };
            // Ignore the fact that this will recurse forever.
            t.test();
        });
    }
}

fn main() {
    let pool = rayon::ThreadPoolBuilder::new()
        .num_threads(4)
        .build()
        .unwrap();

    let value = 0;

    pool.scope(|scope| {
        let t = Test { scope, value: &value };
        t.test();
    });
}
```

Error:
```
error[E0495]: cannot infer an appropriate lifetime due to conflicting requirements
  --> src/main.rs:19:26
   |
19 |           self.scope.spawn(|scope| {
   |  __________________________^
20 | |             let t = Test { scope, v: self.v };
21 | |             t.test();
22 | |         });
   | |_________^
   |
note: first, the lifetime cannot outlive the lifetime `'scope_ref` as defined on the impl at 13:6...
  --> src/main.rs:13:6
   |
13 | impl<'scope_ref, 'scope, 'v> Test<'scope_ref, 'scope, 'v>
   |      ^^^^^^^^^^
note: ...so that the types are compatible
  --> src/main.rs:19:26
   |
19 |           self.scope.spawn(|scope| {
   |  __________________________^
20 | |             let t = Test { scope, v: self.v };
21 | |             t.test();
22 | |         });
   | |_________^
   = note: expected `(&&Test<'_, 'scope, '_>,)`
              found `(&&Test<'scope_ref, 'scope, 'v>,)`
note: but, the lifetime must be valid for the lifetime `'scope` as defined on the impl at 13:18...
  --> src/main.rs:13:18
   |
13 | impl<'scope_ref, 'scope, 'v> Test<'scope_ref, 'scope, 'v>
   |                  ^^^^^^
note: ...so that the types are compatible
  --> src/main.rs:19:20
   |
19 |         self.scope.spawn(|scope| {
   |                    ^^^^^
   = note: expected `&Scope<'_>`
              found `&Scope<'scope>`
```

Rayon version: 1.5.1
Rustc version: 1.55.0-nightly (952fdf2a1 2021-07-05) (doesn't work on stable either)

**Comment by cuviper** [comment]
> but I am faced with lifetime issues, relating to the `|scope| {...` closure outliving the `'scope_ref` lifetime. Is there any way to do this, or is there some type of limitation with the signature of `scope.spawn`?

There is a limitation that `Scope::spawn` requires its closure to outlive the invariant lifetime of the `Scope` itself, which is your `'scope`, not `'scope_ref`. This is because the spawned job is only guaranteed to finish execution some time before the scope is destroyed, so it can't borrow anything with a shorter lifetime than that.

In the example you've given, the problem is that the closure borrows `self` in order to access `self.value`, and this `&self` does not outlive the `'scope`. You could fix this example by extracting `let value = self.value;` beforehand, and also use the `move` keyword on the closure so it captures by-value instead of copying though a reference. (Capturing a reference by value -- I don't blame anyone if that's confusing...)

Here's a [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5746862d8fe76d5875c419d29d6412c7) with that modification, and it compiles and runs successfully. That is, the run hits the timeout due to the never-ending chain of `spawn` -- not exactly recursion as your comment states, but similar.

**Comment by kontheocharis** [comment]
Thank you very much, that fixes it! In hindsight, the error message is rather cryptic, but the solution makes sense.

**Comment by cuviper** [comment]
cc @estebank -- maybe the diagnostic can be improved?

**Comment by estebank** [comment]
@cuviper I'm pretty sure there are tickets covering this case already in our backlog, but if we could have a minimal repro, I would appreciate a new report. We should certainly do a better job of handling these cases.

**Comment by cuviper** [comment]
I opened an issue with a self-contained reproducer: https://github.com/rust-lang/rust/issues/87356
