### ISSUE TITLE
Can we use parking_lot/crossbeam instead of std::sync? (Have heard that it is faster)

### ISSUE THREAD

**Issue by fzyzcjy** [rayon-rs/rayon#896]
Hi thanks for the lib! I wonder whether we can use parking_lot/crossbeam instead of std::sync? I have heard that it is faster. I have checked source code and see rayon seems to use the std::sync.

**Comment by Elabajaba** [comment]
I tested just swapping out the std::sync::Mutex and condvars for parkinglot's, and from scanning the results it doesn't look like it provides a speedup.

https://gist.github.com/Elabajaba/114e6c76b6963bf128bd39491a384f8a

However, after doing a couple more runs, I don't think I trust these benchmarks since I'm seeing variations of up to 40% between runs of the same code (both on the same desktop with fixed boost clocks and nothing else running, run to run variations occur on both Windows and Linux).

**Comment by fzyzcjy** [comment]
Interesting. Does your test case introduce enough parallism? If the mutex is used seldomly instead of frequently, imho it will not show differences.

**Comment by yvt** [comment]
I just ran the same benchmark on Apple M1 (using @Elabajaba's [code](https://github.com/Elabajaba/rayon/commit/cea49593154dc634ff55f8ccd2d13bf638a08da5)), and on average, the `std::sync` version ran 1.05% faster than the `parking_lot` version. There's a significant disparity between test cases. [Google Sheets](https://docs.google.com/spreadsheets/d/1V_082TwJF9UTxUz31hM-bzFcmEZf0kr-UmCsLC_SHrM/edit?usp=sharing)

<img width="750" alt="Screen Shot 2021-11-03 at 0 04 02" src="https://user-images.githubusercontent.com/5253988/139876667-9bb6b717-cd56-4bc5-bc9e-53f9547b0ccf.png">

```shell
$ rustc -Vv
rustc 1.58.0-nightly (db062de72 2021-11-01)
binary: rustc
commit-hash: db062de72b0a064f45b6f86894cbdc7c0ec68844
commit-date: 2021-11-01
host: aarch64-apple-darwin
release: 1.58.0-nightly
LLVM version: 13.0.0

$ cargo bench
...
```

**Comment by nikomatsakis** [comment]
We don't use that much synchronization, so I wouldn't expect a huge impact.
