### ISSUE TITLE
If I have nested parallel loop, how can I change number of threads of inner parallel loop?

### ISSUE THREAD

**Issue by lucidfrontier45** [rayon-rs/rayon#912]
I have a function `f` that uses Rayon's parallel iterator to parallelize heavy computing. I want to run this `f` with different parameters in parallel. This scenario is very often like hyperparameter search in Machine Learning.

Here is a simple example code of the above case. 

```rust
use rayon::prelude::*;
use std::{thread, time::Duration};

fn dummy_func(i: usize) -> usize {
    println!("started {}", i);
    let duration = Duration::from_secs(1);
    (0..4).into_par_iter().for_each(|_| thread::sleep(duration));
    println!("ended {}", i);
    i
}

fn main() {
    let mut res = vec![];
    (0..100)
        .into_par_iter()
        .map(|i| dummy_func(i))
        .collect_into_vec(&mut res);
    dbg!(res);
}
```

If the range of outer loop is large enough, turning off parallelization of the inner loop is preferred.  Now I want to know how I can dynamically change parallelization level of the inner loop function `dummy_func`. Shall I create a dedicated threadpool each time I call `dummy_func` ?

```rust

fn main() {
    let mut res = vec![];
    (0..100)
        .into_par_iter()
        .map(|i| {
            let pool = rayon::ThreadPoolBuilder::new()
                .num_threads(1)
                .build()
                .unwrap();
            pool.install(|| dummy_func(i))
        })
        .collect_into_vec(&mut res);
    dbg!(res);
}
```

**Comment by adamreichold** [comment]
> If the range of outer loop is large enough, turning off parallelization of the inner loop is preferred.

I don't think you need to do anything to achieve this. If all of your threads are busy processing a task from the outer loop, the inner loop should be effectively single-threaded.

(Tasks will be created but they will never leave local task queue of the current thread as the other threads are busy and will there not steal them. This work stealing paradigm will generally keep all of your threads busy will minimal overhead. For example, think about the situation were different iterations of the outer loop will take significantly different amounts of time e.g. due to randomness. Work stealing will still keep are your cores busy whereas if you force the inner loop to be sequential, then some threads will idle as soon as fewer long-running tasks than threads remain.)

((If the remaining task creation overhead is _measured_ to be too high, you can you [`with_min_len`](https://docs.rs/rayon/latest/rayon/iter/trait.IndexedParallelIterator.html#method.with_min_len) on the inner iterator to reduce the number of tasks it can be split into the worst case, but that really is fine-tuning.))

**Comment by lucidfrontier45** [comment]
@adamreichold  Thank you for the explanation.

To check what you said, I changed my code as follows.

```rust
fn dummy_func(i: usize) -> usize {
    println!("started {}", i);
    let duration = Duration::from_secs(1);
    (0..4).into_par_iter().for_each(|j| {
        println!(
            "i = {}, j = {}, thread_id = {:?}",
            i,
            j,
            thread::current().id()
        );
        thread::sleep(duration);
    });
    println!("ended {}", i);
    i
}
```

I confirmed that for the same outer loop index `i` the thread id is also the same ragardless of the inner loop index `j`.

```
started 75
started 12
started 25
started 18
i = 18, j = 0, thread_id = ThreadId(6)
started 0
i = 0, j = 0, thread_id = ThreadId(7)
started 62
i = 75, j = 0, thread_id = ThreadId(9)
i = 12, j = 0, thread_id = ThreadId(2)
i = 25, j = 0, thread_id = ThreadId(4)
started 50
started 37
i = 62, j = 0, thread_id = ThreadId(5)
i = 50, j = 0, thread_id = ThreadId(3)
i = 37, j = 0, thread_id = ThreadId(8)
i = 37, j = 1, thread_id = ThreadId(8)
i = 50, j = 1, thread_id = ThreadId(3)
i = 62, j = 1, thread_id = ThreadId(5)
i = 25, j = 1, thread_id = ThreadId(4)
i = 0, j = 1, thread_id = ThreadId(7)
i = 12, j = 1, thread_id = ThreadId(2)
i = 18, j = 1, thread_id = ThreadId(6)
i = 75, j = 1, thread_id = ThreadId(9)
i = 75, j = 2, thread_id = ThreadId(9)
i = 12, j = 2, thread_id = ThreadId(2)
i = 0, j = 2, thread_id = ThreadId(7)
i = 25, j = 2, thread_id = ThreadId(4)
i = 18, j = 2, thread_id = ThreadId(6)
i = 62, j = 2, thread_id = ThreadId(5)
i = 50, j = 2, thread_id = ThreadId(3)
i = 37, j = 2, thread_id = ThreadId(8)
i = 50, j = 3, thread_id = ThreadId(3)
i = 62, j = 3, thread_id = ThreadId(5)
i = 37, j = 3, thread_id = ThreadId(8)
i = 25, j = 3, thread_id = ThreadId(4)
i = 18, j = 3, thread_id = ThreadId(6)
i = 12, j = 3, thread_id = ThreadId(2)
i = 0, j = 3, thread_id = ThreadId(7)
i = 75, j = 3, thread_id = ThreadId(9)
ended 12
ended 18
...
```
